open file with 'rb'
Pasting images (eg. the ones copied from the web) using CTRL + V throws following errors.

Traceback (most recent call last):
 File "/usr/src/sugar-activities/Write.activity/toolbar.py",
 line 160, in __paste_button_cb px_file.write(data)
TypeError: write() argument must be str, not bytes

image data is of type bytes, change file mode so that it could read byte data.

Regression introduced during Port to Python3 https://github.com/sugarlabs/write-activity/commit/d3bc9756f1fdc9484f75bb450c3c525625278d15

Tested on Ubuntu 20.04 by - Saumya Mishra <2017230@iiitdmj.ac.in>